# Generated by Django 5.2.17 on 2026-09-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_poll_results_visibility_alter_poll_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vote',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
